// Fill out your copyright notice in the Description page of Project Settings.


#include "Zombie.h"
#include "Components/StaticMeshComponent.h"
#include "UObject/ConstructorHelpers.h"
#include "Plant.h"
#include "EstrategiaMovimientoNormal.h"
//#include "EstrategiaMovimientoZigZag.h"

// Sets default values
AZombie::AZombie()
{
 	// Set this actor to call Tick() every frame.  You can turn this off to improve performance if you don't need it.
	PrimaryActorTick.bCanEverTick = true;
	// Registra la función para la detección de colisiones
	//OnActorBeginOverlap.AddDynamic(this, &AZombie::OnOverlapBegin);

	static ConstructorHelpers::FObjectFinder<UStaticMesh> ZombieMesh(TEXT("StaticMesh'/Game/StarterContent/Shapes/Shape_Cone.Shape_Cone'"));
	//static ConstructorHelpers::FObjectFinder<UStaticMesh> ZombieMesh(TEXT("StaticMesh'/Game/StarterContent/Shapes/Shape_Cube.Shape_Cube'"));
	
	ZombieMeshComponent = CreateDefaultSubobject<UStaticMeshComponent>(TEXT("ZombieMesh"));
	//ZombieMeshComponent->SetStaticMesh(ZombieMesh.Object);
	ZombieMeshComponent->SetCollisionProfileName(UCollisionProfile::Pawn_ProfileName);
	ZombieMeshComponent->SetSimulatePhysics(false);
	//ZombieMeshComponent->OnComponentBeginOverlap.AddDynamic(this, &AZombie::OnOverlapBeginFunction);		// set up a notification for when this component hits something
	
	RootComponent = ZombieMeshComponent;

	// Asignar la función de evento a OnOverlapBegin del componente de colisión

	//ZombieMeshComponent->OnComponentHit.AddDynamic(this, &AZombie::OnHit);		// set up a notification for when this component hits something
	ZombieMeshComponent->SetCollisionEnabled(ECollisionEnabled::QueryAndPhysics);

	Tags.Add(TEXT("Enemy"));
	DamageGenerates = 10.0f;
	Health = 50.0f;
	MovementSpeed = 0.1f;
	bCanMove = false;

	ZigzagSpeed = 100.0f;
	ZigzagAmplitude = 1.150f; //en valor de 1.5 va en x de -1500 hasta -1320
	CurrentTime = 0.0f;
	LocationInicial = GetActorLocation();
	
	//ZigzagSpeed = 100.0f;
	//ZigzagAmplitude = 2.0f;
	//ZigzagCounter = 0.0f;
	//ZigzagDirection = 1; // 1 para moverse hacia arriba, -1 para moverse hacia abajo



}


// Called when the game starts or when spawned
void AZombie::BeginPlay()
{
	Super::BeginPlay();
	
	//ABruteForceStrategy* BruteForceStrategy = GetWorld()->SpawnActor<ABruteForceStrategy>(ABruteForceStrategy::StaticClass());
	//BattleShip->AlterManeuvers(BruteForceStrategy);


	AEstrategiaMovimientoNormal* estrategiaMovimientoNormal = GetWorld()->SpawnActor<AEstrategiaMovimientoNormal>(AEstrategiaMovimientoNormal::StaticClass());
	setEstrategiaMovimiento(estrategiaMovimientoNormal);
	//SetLifeSpan(10);

}


//void AZombie::MoveInZigzag(float DeltaTime)
//{
//
//	FVector Location = GetActorLocation();
//	Location.Y -= ZigzagSpeed * DeltaTime;
//	Location.X += FMath::Sin(CurrentTime) * ZigzagAmplitude;
//
//	SetActorLocation(Location);
//
//	CurrentTime += DeltaTime;
//
//}



void AZombie::OnOverlapBeginFunction(UPrimitiveComponent* OverlappedComponent,
									 AActor* OtherActor, UPrimitiveComponent* OtherComp, 
									 int32 OtherBodyIndex, bool bFromSweep,
									 const FHitResult& SweepResult)
{
	GEngine->AddOnScreenDebugMessage(-1, 5.f, FColor::Blue, FString::Printf(TEXT("Estamos aqui")));

	if ((OverlappedComponent != nullptr) && (OtherActor != this))
	{
		GEngine->AddOnScreenDebugMessage(-1, 5.f, FColor::Blue, FString::Printf(TEXT("Estamos aqui")));

		//OtherComp->AddImpulseAtLocation(GetVelocity() * 200.0f, GetActorLocation());
		if (OtherActor->ActorHasTag("Plant"))
		{
			//OtherComp->SetCollisionEnabled(ECollisionEnabled::QueryAndPhysics);

			OtherActor->TakeDamage(DamageGenerates, FDamageEvent(), nullptr, this);
			//OtherComp->DestroyComponent();
			//OtherActor->Destroy();
		}
		else
		{
			// Realiza acciones normales para la colisión con otros actores
			//OnHit(HitComp, OtherActor, OtherComp, NormalImpulse, Hit);
			//OtherComp->SetCollisionEnabled(ECollisionEnabled::NoCollision);

		}
	}
}

void AZombie::OnHit(UPrimitiveComponent* HitComp, AActor* OtherActor,
					UPrimitiveComponent* OtherComp, FVector NormalImpulse, 
					const FHitResult& Hit)
{
	// Only add impulse and destroy projectile if we hit a physics
	//if ((OtherActor != nullptr) && (OtherActor != this) && (OtherComp != nullptr) && OtherComp->IsSimulatingPhysics())
	if ((OtherActor != nullptr) && (OtherActor != this) && (OtherComp != nullptr))
	{
		GEngine->AddOnScreenDebugMessage(-1, 5.f, FColor::Blue, FString::Printf(TEXT("Estamos aqui")));

		//OtherComp->AddImpulseAtLocation(GetVelocity() * 200.0f, GetActorLocation());
		if (OtherActor->ActorHasTag("Plant"))
		{
			//OtherComp->SetCollisionEnabled(ECollisionEnabled::QueryAndPhysics);

			OtherActor->TakeDamage(DamageGenerates, FDamageEvent(), nullptr, this);
			//OtherComp->DestroyComponent();
			//OtherActor->Destroy();
		}
		else
		{
			// Realiza acciones normales para la colisión con otros actores
			//OnHit(HitComp, OtherActor, OtherComp, NormalImpulse, Hit);
			//OtherComp->SetCollisionEnabled(ECollisionEnabled::NoCollision);

		}

	}
}



// Called every frame
void AZombie::Tick(float DeltaTime)
{
	Super::Tick(DeltaTime);

	/*if (Health <= 0.0f)
	{
		Destroy();
	}*/

	//DeltaTimeB += DeltaTime;

	//MoveInZigzag(DeltaTime);
	
	//AEstrategiaMovimientoZigZag::PrecesarDeltaTimer(DeltaTime);

	if (bCanMove && !this->IsHidden())
	{
		//MoveToTarget(FVector(-800.0f, -600.0f, 160.0f));
		moverse();
	}

}

float AZombie::TakeDamage(float Damage, FDamageEvent const& DamageEvent,
						  AController* EventInstigator, AActor* DamageCauser)
{
	// Aquí puedes manejar el daño como desees, por ejemplo, actualizando la salud del actor.
	//GEngine->AddOnScreenDebugMessage(-1, 5.f, FColor::Red, FString::Printf(TEXT("Health Zombie: %f"), this->Health));

	Health -= Damage;
	//GEngine->AddOnScreenDebugMessage(-1, 5.f, FColor::Red, FString::Printf(TEXT("Health Zombie: %f"), this->Health));
	// Devuelve la cantidad de daño que se aplicó realmente.
	return Health;
}

//void AZombie::MoveToTarget(FVector TargetLocation)
//{
//	FVector Direction = TargetLocation - FVector(-800.0f, 400.0f, 160.0f);
//	float DistanceToTarget = FVector::Dist(TargetLocation, FVector(-800.0f, 400.0f, 160.0f));
//
//	// Calcula el desplazamiento en este frame
//	float DeltaMove = MovementSpeed * GetWorld()->DeltaTimeSeconds;
//
//	if (DeltaMove > DistanceToTarget)
//	{
//		// Si el desplazamiento excede la distancia al objetivo, mueve directamente al objetivo
//		this->SetActorLocation(TargetLocation);
//
//	}
//	else
//	{
//		// Mueve el objeto en la direcci�n calculada
//		this->AddActorWorldOffset(Direction * DeltaMove);
//	}
//
//}

void AZombie::setEstrategiaMovimiento(AActor* _estrategiaMovimiento)
{
	estrategiaMovimiento = Cast<IEstrategiaMovimiento>(_estrategiaMovimiento);

	//Log Error if the cast failed
	if (!estrategiaMovimiento)
	{
		GEngine->AddOnScreenDebugMessage(-1, 15.f, FColor::Red, TEXT("Invalid Cast! See Output log for more details"));
		UE_LOG(LogTemp, Error, TEXT("Moverse(): The Actor is not a estrategia de movimiento!Are you sure that the Actor implements that interface ? "));
	}

}

void AZombie::moverse()
{
	estrategiaMovimiento->moverseEstrategia(this, FVector(-800.0f, -600.0f, 160.0f));
}
